#!/bin/bash

# Detener el script si algo falla
set -e

# Variables globales solo para la instalacion.
ROOT_FOLDER="~/"
PROJECT_NAME="moo-ubuntu"
ROOT_FOLDER_PROJECT=$ROOT_FOLDER"/$PROJECT_NAME"

SHARE_DRIVE_TARGET_SIZE="214748364800"

ROOT_FOLDER_SHARED="moo-shared"
MOUNTED_FOLDER="/mnt/$ROOT_FOLDER_SHARED"

WORKSPACE_NAME="moo-microservices"
DOCKER_ENGINE="docker-engine"
DOCKER_STATE="docker-state"

WORKSPACE_DIR="$MOUNTED_FOLDER/$WORKSPACE_NAME"
DOCKER_SPACE="$MOUNTED_FOLDER/$DOCKER_ENGINE"
DOCKER_VOLUME="$MOUNTED_FOLDER/$DOCKER_STATE"
DOCKER_WORKSPACE_FOLDER="~/$PROJECT_NAME/dockers"
